// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drmmylpfcgaaeqchtoxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybW15bHBmY2dhYWVxY2h0b3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0Mjg2ODQsImV4cCI6MjA4NDAwNDY4NH0.Zjb4jDOWSAk_-v0uI-OUC2mu53NMeDkJm-M8jL8xf0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});